config/routes.rb
Rails.application.routes.draw do
  root "guest_transactions#new"

  # Webhook for Unifi Controller
  get "guest" => "guests_controller#guest"

  resources :guest_transactions, only: [:new, :create, :show]
end

app/models/guest_transaction.rb
class GuestTransaction
  include Virtus.model
  include ActiveModel::Model

  # Guest
  attribute :device_address
  attribute :access_point_address
  attribute :first_name
  attribute :last_name
  attribute :email
  attribute :url

  # Transaction
  attribute :cc_number
  attribute :cc_expiry_month
  attribute :cc_expiry_year
  attribute :city
  attribute :state
  attribute :zip
  attribute :security_code
  attribute :package_id

  # Validations
  validates :package_id,                presence: true, format: { with: /\A([0-9a-f]{4}-?){7}[0-9a-f]{4}\z/i, multiline: true }
  validates :device_address,            presence: true, format: { with: /^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$/, multiline: true }
  validates :access_point_address,      presence: true, format: { with: /^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$/, multiline: true }
  validates :url,                       format: { with: URI.regexp }, if: ->{ url.present? }
  validates :first_name, :last_name,    presence: true, if: ->{ package_id != Figaro.env.free_package_id }
  validates :cc_number, :security_code, presence: true, if: ->{ package_id != Figaro.env.free_package_id }
  validates :cc_expiry_month,           presence: true, if: ->{ package_id != Figaro.env.free_package_id }
  validates :cc_expiry_year,            presence: true, if: ->{ package_id != Figaro.env.free_package_id }
  validates :city, :state, :zip,        presence: true, if: ->{ package_id != Figaro.env.free_package_id }
  validates :state,                     inclusion: { in: CS.states(:us).values }, if: ->{ package_id != Figaro.env.free_package_id }

  validate :package_is_available?

  def save
    @guest = FindOrCreateGuest.call(guest_params).guest
    return false unless @guest.valid?
    @transaction_information = CreateTransactionInformation.call(transaction_params).transaction_information
    @transaction_information.valid?
  end

  def packages
    # Package selection
    @packages ||= FindPackagesForDeviceAddress.call(device_address: device_address).packages
  end

  def package_is_available?
    packages.map(&:id).include?(package_id)
  end

  def self.find(id)
    FindGuest.call(id: id).guest
  end
end

app/models/package.rb
class Package
  include Virtus.model

  attribute :id, String
  attribute :name, String
  attribute :description, String
  attribute :charged_as, String
  attribute :price_cents, Integer
  attribute :duration_minutes, Integer
  attribute :limit_up, Integer
  attribute :limit_down, Integer
  attribute :limit_quota, Integer
  attribute :currency, String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guest_transactions_controller.rb
class GuestTransactionsController < ApplicationController
  def new
    # New guest transaction
    @guest_transaction = GuestTransaction.new(guest_transaction_params)
  end

  def show
    @guest_transaction = GuestTransaction.find(guest_transaction_params[:id])
  end

  def create
    @guest_transaction = GuestTransaction.new(guest_transaction_params)

    respond_to do |format|
      if @guest_transaction.save
        format.html { redirect_to @guest_transaction }
      else
        format.html { render :new }
      end
    end
  end

  private

  def guest_transaction_params
    params.permit(
      :id,
      :device_address,
      :access_point_address,
      :url,
      :first_name,
      :last_name,
      :email,
      :cc_number,
      :cc_expiry_month,
      :cc_expiry_year,
      :city,
      :state,
      :zip,
      :security_code,
      :package_id
    )
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_filter :redirect_authorized_guests

  # GET /guest
  def guest
    # This just picks up the webhook, parses it, and shows
    # the actual splash page where plans are picked

    # From https://community.ubnt.com/t5/UniFi-Wireless/external-hotspot-portal/td-p/419845
    # /guest/?id=20:aa:4b:95:bc:9d&ap=00:27:22:e4:ce:79&t=1363610350&url=http://facebook.com/&ssid=Test%20SSID

    redirect_to new_guest_transaction_path(
      device_address: guest_params[:id],
      access_point_address: guest_params[:ap],
      url: redirect_url
    )
  end

  private

  def guest_params
    params.permit(:id, :ap, :url)
  end

  def redirect_authorized_guests
    if CheckGuestAuthorization.call(device_address: guest_params[:ap]).success?
      redirect_to redirect_url
    end
  end

  def redirect_url
    return Figaro.env.app_host unless guest_params[:url] && URI.parse(guest_params[:url]).host
    guest_params[:url]
  rescue URI::InvalidURIError
    Figaro.env.app_host
  end
end

app/controllers/portal_controller.rb
class PortalController < ApplicationController
  # GET /guest
  def new
    # This just picks up the webhook, parses it, and shows
    # the actual splash page where plans are picked

    # From https://community.ubnt.com/t5/UniFi-Wireless/external-hotspot-portal/td-p/419845
    # /guest/?id=20:aa:4b:95:bc:9d&ap=00:27:22:e4:ce:79&t=1363610350&url=http://facebook.com/&ssid=Test%20SSID

    @device_address = params[:id]
    @access_point_address = params[:ap]
    @url = params[:url]

    @packages = FindPackagesForDeviceAddress.call(device_address: @device_address)

    # Fill in billing info, guest info, etc.
    @guest_transaction = GuestTransaction.new
  end

  def create
    authorize_guest = AuthorizeGuest.call(
      params: guest_transaction_params
    )

    @guest_transaction = authorize_guest.guest_transaction

    respond_to do |format|
      format.html do
        if authorize_guest.success?
          redirect_to authorize_guest.url
        else
          render :new
        end
      end
    end
  end

  private

  def guest_transaction_params
    params.permit(
      guest: [:device_address, :access_point_address, :url],
      transaction: [:first_name, :last_name, :cc_number, :city, :state, :zip, :security_code]
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guest_transactions_helper.rb
module GuestTransactionsHelper
end

app/views/guest_transactions/_form.html.erb
<%= form_for(@guest_transaction) do |f| %>
  <% if @guest_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guest_transaction.errors.count, "error") %> prohibited this guest_transaction from being saved:</h2>

      <ul>
      <% @guest_transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guest_transactions/edit.html.erb
<h1>Editing Guest Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @guest_transaction %> |
<%= link_to 'Back', guest_transactions_path %>

app/views/guest_transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Guest Transactions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guest_transactions.each do |guest_transaction| %>
      <tr>
        <td><%= link_to 'Show', guest_transaction %></td>
        <td><%= link_to 'Edit', edit_guest_transaction_path(guest_transaction) %></td>
        <td><%= link_to 'Destroy', guest_transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guest transaction', new_guest_transaction_path %>

app/views/guest_transactions/new.html.erb
<%= render "shared/notice" %>

<h1>Summerfell Wi-Fi Hotspot</h1>

<p>
Welcome to the Summerfell Wi-Fi network. Please select a plan from the options below:
</p>

<%= render "shared/form_errors", model: @guest_transaction %>

<%= form_for @guest_transaction, html: {role: "form"} do |f| %>
  <%= collection_radio_buttons(:guest_transaction, :package_id, @packages, :id, :name) %>

  <%= f.hidden_field(:device_address, value: @device_address) %>
  <%= f.hidden_field(:access_point_address, value: @access_point_address) %>
  <%= f.hidden_field(:url, value: @url) %>

  <%= f.label :first_name, class: "control-label" %>
  <%= f.text_field :first_name, class: "form-control" %>

  <%= f.label :last_name, class: "control-label" %>
  <%= f.text_field :last_name, class: "form-control" %>

  <%= f.label :email, class: "control-label" %>
  <%= f.email_field :email, class: "form-control", placeholder: "Enter your email if you want a receipt." %>

  <%= f.label :cc_number, "Credit Card Number", class: "control-label" %>
  <%= f.text_field :cc_number, class: "form-control" %>

  <%= f.label :cc_expiry_month, "Credit Card Expiration Month", class: "control-label" %>
  <%= f.select :cc_expiry_month, (1..12).to_a, {}, class: "form-control", size: 4 %>

  <%= f.label :cc_expiry_year, "Credit Card Expiration Year", class: "control-label" %>
  <%= f.select :cc_expiry_year, (2016..2030).to_a, {}, class: "form-control", size: 8 %>

  <%= f.label :security_code, class: "control-label" %>
  <%= f.text_field :security_code, class: "form-control" %>

  <%= f.label :city, class: "control-label" %>
  <%= f.text_field :city, class: "form-control" %>

  <%= f.label :state, class: "control-label" %>
  <%= f.select :state, CS.states(:us).values, {}, class: "form-control" %>

  <%= f.label :zip, "Zip Code", class: "control-label" %>
  <%= f.text_field :zip, class: "form-control" %>

  <%= f.submit 'Submit', class: "btn btn-default" %>
<% end %>

app/views/guest_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_guest_transaction_path(@guest_transaction) %> |
<%= link_to 'Back', guest_transactions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SouthGate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_form_errors.html.erb
<% if model.errors.any? %>
  <div class="row">
    <div class="col-lg-12">
      <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <i class="fa fa-info-circle"></i> <%= pluralize(model.errors.count, "error") %> prohibited this build from being saved:
        <ul>
          <% model.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div><!-- /.row -->
<% end %>

app/views/shared/_notice.html.erb
<div class="row">
  <div class="col-lg-12">
    <% if notice.present? %>
      <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <i class="fa fa-info-circle"></i><%= notice %>
      </div>
    <% end %>
  </div>
</div>
<!-- /.row -->